### ISSUE TITLE
Provide any build compatible with Ubuntu 18.04 (which is LTS)

### ISSUE THREAD

**Issue by Drugoy** [ungoogled-software/ungoogled-chromium-portablelinux#116] opened 2021-10-25 19:29 UTC
`./ungoogled-chromium_91.0.4472.164-1.1.AppImage`
results into
```
/tmp/.mount_ungoogu7xwUu/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_ungoogu7xwUu/opt/google/chrome/chrome)
/tmp/.mount_ungoogu7xwUu/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_ungoogu7xwUu/opt/google/chrome/chrome)
```
because
```
ls -lash /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libm.so.6
0 lrwxrwxrwx 1 root root 12 Dec  7  2020 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.27.so*
0 lrwxrwxrwx 1 root root 12 Dec  7  2020 /lib/x86_64-linux-gnu/libm.so.6 -> libm-2.27.so
```

**Comment by Eloston** [comment] 2021-10-29 18:36
Closing as duplicate of #107

**Closed by Eloston** 2021-10-29 18:36 UTC
